### PR TITLE
E2E test: Ommit error ifNotFound during NFD cleanup

### LINKED ISSUE #642: Fix e2e tests
The e2e tests fail (see https://github.com/NVIDIA/k8s-device-plugin/actions/runs/8660409546/job/23748292556) with the following shown:
```
FAILED] Unexpected error:
      <*errors.StatusError | 0xc0000cc8c0>: 
      nodefeatures.nfd.k8s-sigs.io "holodeck" not found
      {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "nodefeatures.nfd.k8s-sigs.io \"holodeck\" not found",
              Reason: "NotFound",
              Details: {
                  Name: "holodeck",
                  Group: "nfd.k8s-sigs.io",
                  Kind: "nodefeatures",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
  occurred
  In [AfterEach] at: /home/runner/work/k8s-device-plugin/k8s-device-plugin/tests/e2e/common/kubernetes.go:187 @ 04/12/24 10:15:04.46
```

This happens when trying to delete the nfd namespace, but it is aready found to not exist. I believe the check needs to be updated to include logic such as https://github.com/kubernetes-sigs/node-feature-discovery/blob/624c02e1e2b5a4340b4921ebc04dd751c200f452/pkg/nfd-gc/nfd-gc.go#L79-L90

Something like (although I must admit that I don't know what the equivalent Gomega expressions are):
```
diff --git a/tests/e2e/common/kubernetes.go b/tests/e2e/common/kubernetes.go
index a30c763f..71c634ea 100644
--- a/tests/e2e/common/kubernetes.go
+++ b/tests/e2e/common/kubernetes.go
@@ -174,7 +174,7 @@ func CleanupNodeFeatureRules(ctx context.Context, cli *nfdclient.Clientset, name
 		By("Deleting NodeFeatureRule objects from the cluster")
 		for _, nfr := range nfrs.Items {
 			err = cli.NfdV1alpha1().NodeFeatureRules().Delete(ctx, nfr.Name, metav1.DeleteOptions{})
-			Expect(err).Or(NotTo(HaveOccurred()), MatchError(errors.New("not found"))))
+			Expect(err).Or(NotTo(HaveOccurred()), MatchError(errors.New("not found")))
 		}
 	}
 
@@ -185,7 +185,7 @@ func CleanupNodeFeatureRules(ctx context.Context, cli *nfdclient.Clientset, name
 		By("Deleting NodeFeature objects from namespace " + namespace)
 		for _, nf := range nfs.Items {
 			err = cli.NfdV1alpha1().NodeFeatures(namespace).Delete(ctx, nf.Name, metav1.DeleteOptions{})
-			Expect(err).Or(NotTo(HaveOccurred()), MatchError(errors.New("not found"))))
+			Expect(err).Or(NotTo(HaveOccurred()), MatchError(errors.New("not found")))
 		}
 	}
 }
```

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Fixes #642

### CODE REVIEW

File: tests/e2e/common/kubernetes.go [hunk 1]
```diff
@@ -164,27 +165,43 @@ func CleanupNode(ctx context.Context, cs clientset.Interface) {
...
-			Expect(err).NotTo(HaveOccurred())
+			if err != nil {
+				if errors.IsNotFound(err) {
+					// Ommitted error
+					continue
+				} else {
+					Expect(err).NotTo(HaveOccurred())
+				}
+			}
+
```
Comment (elezar) [inline tests/e2e/common/kubernetes.go:185]:
```suggestion
			if errors.IsNotFound(err) {
				// Omitted error
				continue
			} else {
				Expect(err).NotTo(HaveOccurred())
			}
```

File: tests/e2e/common/kubernetes.go [hunk 2]
```diff
@@ -164,27 +165,43 @@ func CleanupNode(ctx context.Context, cs clientset.Interface) {
...
 			err = cli.NfdV1alpha1().NodeFeatures(namespace).Delete(ctx, nf.Name, metav1.DeleteOptions{})
-			Expect(err).NotTo(HaveOccurred())
+			if err != nil {
+				if errors.IsNotFound(err) {
+					// Ommitted error
+					continue
+				} else {
+					Expect(err).NotTo(HaveOccurred())
+				}
+			}
```
Comment (elezar) [inline tests/e2e/common/kubernetes.go:204]:
```suggestion
			if errors.IsNotFound(err) {
				// Omitted error
				continue
			} else {
				Expect(err).NotTo(HaveOccurred())
			}
```

**Review by elezar — CHANGES_REQUESTED** [review]
We don't really need the two levels of nesting.

File: tests/e2e/common/kubernetes.go [hunk 3]
```diff
@@ -164,27 +165,38 @@ func CleanupNode(ctx context.Context, cs clientset.Interface) {
 	}
 }
 
-func CleanupNodeFeatureRules(ctx context.Context, cli *nfdclient.Clientset, namespace string) {
-	// Drop NodeFeatureRule objects
+func CleanupNodeFeatures(ctx context.Context, cli *nfdclient.Clientset, namespace string) {
+	// Clean NodeFeatureRule objects
 	nfrs, err := cli.NfdV1alpha1().NodeFeatureRules().List(ctx, metav1.ListOptions{})
```
Comment (elezar) [inline tests/e2e/common/kubernetes.go:170]: Question: Don't we have to do the same thing here? Does `List` return `ErrNotFound` if there are no nodeFeatureRules?

File: tests/e2e/common/kubernetes.go [hunk 4]
```diff
@@ -164,27 +165,38 @@ func CleanupNode(ctx context.Context, cs clientset.Interface) {
...
 	Expect(err).NotTo(HaveOccurred())
 
 	if len(nfrs.Items) != 0 {
 		By("Deleting NodeFeatureRule objects from the cluster")
 		for _, nfr := range nfrs.Items {
```
Comment (elezar) [inline tests/e2e/common/kubernetes.go:175]: Question: Could we be deleting node feature rules that are NOT controlled by our components?

File: tests/e2e/common/kubernetes.go (hunk 3 above)
Comment (ArangoGutierrez) [reply tests/e2e/common/kubernetes.go:170]: umm, it is possible, yes

File: tests/e2e/common/kubernetes.go [hunk 5]
```diff
@@ -164,27 +165,46 @@ func CleanupNode(ctx context.Context, cs clientset.Interface) {
 	}
 }
 
-func CleanupNodeFeatureRules(ctx context.Context, cli *nfdclient.Clientset, namespace string) {
-	// Drop NodeFeatureRule objects
+func CleanupNodeFeatures(ctx context.Context, cli *nfdclient.Clientset, namespace string) {
+	// Clean NodeFeatureRule objects
 	nfrs, err := cli.NfdV1alpha1().NodeFeatureRules().List(ctx, metav1.ListOptions{})
```
Comment (elezar) [inline tests/e2e/common/kubernetes.go:170]: Given that each of these have multiple levels of nesting, let's move this to a separate `cleanupNodeFeatureRules` function with a quick return if `errors.IsNotFound`?

File: tests/e2e/common/kubernetes.go [hunk 6]
```diff
@@ -164,27 +165,46 @@ func CleanupNode(ctx context.Context, cs clientset.Interface) {
...
+					continue
+				} else {
+					Expect(err).NotTo(HaveOccurred())
+				}
+			}
 		}
 	}
 
+	// Clean NodeFeature objects
 	nfs, err := cli.NfdV1alpha1().NodeFeatures(namespace).List(ctx, metav1.ListOptions{})
```
Comment (elezar) [inline tests/e2e/common/kubernetes.go:191]: This can also be a separate function and then we can quick-return when `errors.IsNotFound` is triggered.

File: tests/e2e/gpu-feature-discovery_test.go [hunk 7]
```diff
@@ -143,9 +143,9 @@ var _ = NVDescribe("GPU Feature Discovery", func() {
 			// Delete Helm release
 			err := helmClient.UninstallReleaseByName(helmReleaseName)
 			Expect(err).NotTo(HaveOccurred())
-			// cleanup node
+			// Cleanup node
 			common.CleanupNode(ctx, f.ClientSet)
-			common.CleanupNodeFeatureRules(ctx, nfdClient, f.Namespace.Name)
+			common.CleanupNodeFeatures(ctx, nfdClient, f.Namespace.Name)
```
Comment (elezar) [inline tests/e2e/gpu-feature-discovery_test.go:148]: Question: Since we delete both `NodeFeatures` and `NodeFeatureRules` in this function is there a better name for the collection of these two?

**Review by elezar — COMMENTED** [review]
I think factoring the two deletion blocks into two separate blocks will make things much clearer and reduce nesting levels.

File: tests/e2e/gpu-feature-discovery_test.go (hunk 7 above)
Comment (ArangoGutierrez) [reply tests/e2e/gpu-feature-discovery_test.go:148]: `NFDObjects` ?

**Comment by ArangoGutierrez** [comment]
> I think factoring the two deletion blocks into two separate blocks will make things much clearer and reduce nesting levels.

How about now?

File: tests/e2e/common/kubernetes.go [hunk 8]
```diff
@@ -164,27 +165,53 @@ func CleanupNode(ctx context.Context, cs clientset.Interface) {
...
-func CleanupNodeFeatureRules(ctx context.Context, cli *nfdclient.Clientset, namespace string) {
-	// Drop NodeFeatureRule objects
-	nfrs, err := cli.NfdV1alpha1().NodeFeatureRules().List(ctx, metav1.ListOptions{})
-	Expect(err).NotTo(HaveOccurred())
+// cleanupNodeFeatures deletes all NodeFeature objects in the given namespace
+func cleanupNodeFeatures(ctx context.Context, cli *nfdclient.Clientset, namespace string) {
+	nfs, err := cli.NfdV1alpha1().NodeFeatures(namespace).List(ctx, metav1.ListOptions{})
+	if errors.IsNotFound(err) {
+		// Omitted error, nothing to do.
+	} else {
```
Comment (elezar) [inline tests/e2e/common/kubernetes.go:173]:
```suggestion
	if errors.IsNotFound(err) {
		return
	}
```

File: tests/e2e/common/kubernetes.go [hunk 9]
```diff
@@ -164,27 +165,53 @@ func CleanupNode(ctx context.Context, cs clientset.Interface) {
...
+}
 
-	nfs, err := cli.NfdV1alpha1().NodeFeatures(namespace).List(ctx, metav1.ListOptions{})
-	Expect(err).NotTo(HaveOccurred())
+// cleanupNodeFeatureRules deletes all NodeFeatureRule objects
+func cleanupNodeFeatureRules(ctx context.Context, cli *nfdclient.Clientset) {
+	nfrs, err := cli.NfdV1alpha1().NodeFeatureRules().List(ctx, metav1.ListOptions{})
+	if errors.IsNotFound(err) {
+		// Omitted error, nothing to do.
+	} else {
```
Comment (elezar) [inline tests/e2e/common/kubernetes.go:196]:
```suggestion
	if errors.IsNotFound(err) {
		return
	}
```

**Review by elezar — CHANGES_REQUESTED** [review]
Last comment. Let's quick-return to reduce nesting.

File: tests/e2e/common/kubernetes.go [hunk 10]
```diff
@@ -164,27 +165,55 @@ func CleanupNode(ctx context.Context, cs clientset.Interface) {
...
-	nfrs, err := cli.NfdV1alpha1().NodeFeatureRules().List(ctx, metav1.ListOptions{})
-	Expect(err).NotTo(HaveOccurred())
+// cleanupNodeFeatures deletes all NodeFeature objects in the given namespace
+func cleanupNodeFeatures(ctx context.Context, cli *nfdclient.Clientset, namespace string) {
+	nfs, err := cli.NfdV1alpha1().NodeFeatures(namespace).List(ctx, metav1.ListOptions{})
+	if errors.IsNotFound(err) {
+		// Omitted error, nothing to do.
+		return
+	} else {
+		Expect(err).NotTo(HaveOccurred())
```
Comment (elezar) [inline tests/e2e/common/kubernetes.go:175]:
```suggestion
	}
	Expect(err).NotTo(HaveOccurred())
```

Since we return we don't need the `else` block.

**Review by elezar — CHANGES_REQUESTED** [review]
Remove the `else` blocks. This is what I mean by removing indentation.

File: tests/e2e/common/kubernetes.go [hunk 11]
```diff
@@ -164,27 +165,53 @@ func CleanupNode(ctx context.Context, cs clientset.Interface) {
...
+
+	if len(nfs.Items) != 0 {
+		By("Deleting NodeFeature objects from namespace " + namespace)
+		for _, nf := range nfs.Items {
+			err = cli.NfdV1alpha1().NodeFeatures(namespace).Delete(ctx, nf.Name, metav1.DeleteOptions{})
+			if errors.IsNotFound(err) {
+				// Omitted error
+				continue
+			} else {
+				Expect(err).NotTo(HaveOccurred())
```
Comment (elezar) [inline tests/e2e/common/kubernetes.go:185]: Nit: technically we can drop this else block too. Not a blocker.

File: tests/e2e/common/kubernetes.go [hunk 12]
```diff
@@ -164,27 +165,53 @@ func CleanupNode(ctx context.Context, cs clientset.Interface) {
...
-	Expect(err).NotTo(HaveOccurred())
-
-	if len(nfs.Items) != 0 {
-		By("Deleting NodeFeature objects from namespace " + namespace)
-		for _, nf := range nfs.Items {
-			err = cli.NfdV1alpha1().NodeFeatures(namespace).Delete(ctx, nf.Name, metav1.DeleteOptions{})
-			Expect(err).NotTo(HaveOccurred())
-		}
-	}
+func CleanupNFDObjects(ctx context.Context, cli *nfdclient.Clientset, namespace string) {
```
Comment (elezar) [inline tests/e2e/common/kubernetes.go:214]: nit: If we have the public function before the others the diff might align better and the file would be easier to skim from top to bottom.

**Review by elezar — APPROVED** [review]
I only have some minor nits left.

Thanks for the patience.

**Review by elezar — APPROVED** [review]
